# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170902_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Roboczy'), ('publish', 'Publiczny')], default='draft', max_length=10),
        ),
    ]
